---
$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
version: "0.2"
language:
  - "en"
  - "en-GB"
dictionaries:
  - "aws"
  - "bash"
  - "companies"
  - "csharp"
  - "css"
  - "cryptocurrencies"
  - "data-science"
  - "docker"
  - "dotnet"
  - "en-slang"
  - "filetypes"
  - "fullstack"
  - "gaming-terms"
  - "git"
  - "golang"
  - "html"
  - "k8s"
  - "makefile"
  - "markdown"
  - "medicalterms"
  - "networking-terms"
  - "node"
  - "npm"
  - "people-names"
  - "php"
  - "pokemon"
  - "powershell"
  - "python"
  - "ruby"
  - "shell"
  - "software-terms"
  - "sql"
  - "terraform"
  - "typescript"
  - "web-services"
words:
  - "alaffia"
  - "amazonlinux"
  - "apikey"
  - "autoscaler"
  - "bchoy"
  - "bchoytest"
  - "boto"
  - "botocore"
  - "botting"
  - "buildcache"
  - "catppuccin"
  - "choy"
  - "clinicos"
  - "cmdargs"
  - "computex"
  - "coreweave"
  - "cuda"
  - "cudnn"
  - "cyclegan"
  - "fargate"
  - "fastapi"
  - "feroxbuster"
  - "ffuf"
  - "girsh"
  - "grabbable"
  - "hashcat"
  - "helmfile"
  - "helmfiles"
  - "imaginaire"
  - "impacket"
  - "joomscan"
  - "justfile"
  - "legba"
  - "letsencrypt"
  - "loguru"
  - "macchiato"
  - "mesher"
  - "metasploit"
  - "ndarray"
  - "nerdfonts"
  - "netcode"
  - "netexec"
  - "nixos"
  - "nixpkgs"
  - "postop"
  - "preop"
  - "presync"
  - "psycopg"
  - "pulumi"
  - "pydantic"
  - "pyproject"
  - "pysetup"
  - "pytest"
  - "rcat"
  - "rustscan"
  - "searchsploit"
  - "sqlalchemy"
  - "supabase"
  - "torchvision"
  - "untargetable"
  - "upscaler"
  - "uvcgan"
  - "uvicorn"
  - "venv"
  - "wandb"
  - "whatweb"
ignorePaths:
  - ".git"
  - ".venv"
  - "node_modules"
